# Generated by Django 5.2 on 2026-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_api', '0002_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generation',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generation',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
